kind: Service
apiVersion: v1
metadata:
  name: account-manager
  labels:
    app: go
spec:
  selector:
    app: go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "account-manager"
        dapr.io/app-port: "50001"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: go
        image: ghcr.io/hello-slide/account-manager@sha256:00ea353bf8e4272573bb2eb1d5795d513823b468b4eb488c3d2c14af77d924a8
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
