kind: Service
apiVersion: v1
metadata:
  name: account-manager
  labels:
    app: account-manager
spec:
  selector:
    app: account-manager
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager
  labels:
    app: account-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-manager
  template:
    metadata:
      labels:
        app: account-manager
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "account-manager"
        dapr.io/app-port: "50001"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: account-manager
        image: ghcr.io/hello-slide/account-manager@sha256:050ccf5c56d74b9e9eaf36ec2962c3300e2e00de5799897aa9d8900a037364ee
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: account-manager-secret
              key: google_client
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: account-manager-secret
              key: google_secret
        - name: SEED
          valueFrom:
            secretKeyRef:
              name: account-manager-secret
              key: seed
        - name: TOKEN_MANAGER
          value: "token-manager"
        - name: USER_DATA_STATE
          value: "user-data-state"
        - name: USER_EMAIL_STATE
          value: "user-email-state"
        - name: REFRESH_TOKEN_STATE
          value: "login-token-state"
        - name: API_URL
          value: "https://api.hello-slide.jp"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
