kind: Service
apiVersion: v1
metadata:
  name: slide-manager
  labels:
    app: slide-manager
spec:
  selector:
    app: slide-manager
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slide-manager
  labels:
    app: slide-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slide-manager
  template:
    metadata:
      labels:
        app: slide-manager
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "slide-manager"
        dapr.io/app-port: "50001"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: slide-manager
        image: ghcr.io/hello-slide/slide-manager@sha256:1020aeb87526a6634e71460fc82811b63d5e1dd85449214fd150d2b3636ca2b9
        env:
        - name: KEY
          valueFrom:
            secretKeyRef:
              name: slide-manager-secret
              key: json
        - name: SLIDE_CONFIG
          value: "slide-config-state"
        - name: TOKEN_MANAGER
          value: "token-manager"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
