apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-manager
  labels:
    app: token-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-manager
  template:
    metadata:
      labels:
        app: token-manager
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "token-manager"
        dapr.io/app-port: "3000"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: token-manager
        image: ghcr.io/hello-slide/token-manager@sha256:99686402f12df2837c82359015e3e12346c09160d1d9fbfc638367dab33cd645
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
