apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-manager
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "token-manager"
        dapr.io/app-port: "3000"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: go
        image: ghcr.io/hello-slide/token-manager@sha256:f7822fe15a9dc4dd7918ca534aaeac24386fad6b4226754a2d24b625c96b570e
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
