kind: Service
apiVersion: v1
metadata:
  name: token-manager
  labels:
    app: go
spec:
  selector:
    app: go
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-manager
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "token-manager"
        dapr.io/app-port: "3000"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: go
        image: ghcr.io/hello-slide/token-manager@sha256:c45153dcf939e27485355f331884ab2db51da1d307660f9a111131d990be91fd
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
